package com.example.test.responsse;

import com.google.gson.annotations.SerializedName;

import java.util.List;

public class LoginReturn {
    @SerializedName("EmailID") public String emailID;
    @SerializedName("PreferredLocationName") public String preferredLocationName;
    @SerializedName("ShopAddress") public String shopAddress;
    @SerializedName("Reschedule") public String reschedule;
    @SerializedName("GmailGoogleCalendar") public String gmailGoogleCalendar;
    @SerializedName("OTP") public String oTP;
    @SerializedName("CustomerID") public String customerID;
    @SerializedName("HomeBGColor_AppStatus") public String homeBGColorAppStatus;
    @SerializedName("IsAllowGoogleCalendar") public String isAllowGoogleCalendar;
    @SerializedName("IsHideRegistration") public String isHideRegistration;
    @SerializedName("CustomerVoyoDetails") public Object customerVoyoDetails;
    @SerializedName("VideoSize") public String videoSize;
    @SerializedName("StorageLimit") public String storageLimit;
    @SerializedName("AllowChangeStatus") public String allowChangeStatus;
    @SerializedName("IsShowYear") public String isShowYear;
    @SerializedName("And_DateTimeMerFormat") public String andDateTimeMerFormat;
    @SerializedName("IsHideRatings") public String isHideRatings;
    @SerializedName("AppToolsEnabled") public String appToolsEnabled;
    @SerializedName("Modified_by") public String modifiedBy;
    @SerializedName("TimeZone") public String timeZone;
    @SerializedName("BackgroundImage") public String backgroundImage;
    @SerializedName("isHide_offerCode") public String isHideOfferCode;
    @SerializedName("SkipLogin") public String skipLogin;
    @SerializedName("IsShowQuotes") public String isShowQuotes;
    @SerializedName("ButtonBGColor") public String buttonBGColor;
    @SerializedName("Modified_Date") public String modifiedDate;
    @SerializedName("IsVVSubscribed") public String isVVSubscribed;
    @SerializedName("IsHideComments") public String isHideComments;
    @SerializedName("LocaleCode") public String localeCode;
    @SerializedName("CustomerSK") public String customerSK;
    @SerializedName("addrdate") public String addrdate;
    @SerializedName("PreferredLocation") public String preferredLocation;
    @SerializedName("IconColor") public String iconColor;
    @SerializedName("AppointmentNotification") public String appointmentNotification;
    @SerializedName("IsHideTime") public String isHideTime;
    @SerializedName("countryCode") public String countryCode;
    @SerializedName("BTGroupSK") public int bTGroupSK;
    @SerializedName("IsOTPVerified") public String isOTPVerified;
    @SerializedName("TitleTextColor") public String titleTextColor;
    @SerializedName("Created_by") public String createdBy;
    @SerializedName("ForceUpdate") public String forceUpdate = "0";
    @SerializedName("TimeLimit") public String timeLimit;
    @SerializedName("ShopSK") public String shopSK;
    @SerializedName("Offerimage") public String offerimage;
    @SerializedName("FirstName") public String firstName;
    @SerializedName("IsHideSignup") public String isHideSignup;
    @SerializedName("AllowOfferimage") public String allowOfferimage;
    @SerializedName("NoOfServiceLanes") public String noOfServiceLanes;
    @SerializedName("TabFontColor") public String tabFontColor;
    @SerializedName("UsageLimit") public String usageLimit;
    @SerializedName("ShopcountryCode") public String shopcountryCode;
    @SerializedName("ChatNotification") public String chatNotification;
    @SerializedName("And_DateTimeUTCFormat") public String andDateTimeUTCFormat;
    @SerializedName("AllowAddVehicle") public String allowAddVehicle;
    @SerializedName("ShopName") public String shopName;
    @SerializedName("TopStatusBarBGColor") public String topStatusBarBGColor;
    @SerializedName("HideMultiLanguage") public String hideMultiLanguage;
    @SerializedName("VolumeUnitCode") public String volumeUnitCode;
    @SerializedName("DateDisplayFormat") public String dateDisplayFormat;
    @SerializedName("VehiclesforSaleLimit") public String vehiclesforSaleLimit;
    @SerializedName("ShowPaymentOption") public String showPaymentOption;
    @SerializedName("ButtonTextColor") public String buttonTextColor;
    @SerializedName("tab_chk") public String tabChk;
    @SerializedName("VolumeUnit") public String volumeUnit;
    @SerializedName("StripeSecretKey") public String stripeSecretKey;
    @SerializedName("TimeDisplayFormat") public String timeDisplayFormat;
    @SerializedName("AMMApikey") public String aMMApikey;
    @SerializedName("ShopcountryName") public String shopcountryName;
    @SerializedName("IsAllowVehiclesforSale") public String isAllowVehiclesforSale;
    @SerializedName("StartDay") public String startDay;
    @SerializedName("LengthUnit") public String lengthUnit;
    @SerializedName("MobileStatusBar") public String mobileStatusBar;
    @SerializedName("top_chk") public String topChk;
    @SerializedName("AllowAddCustomer") public String allowAddCustomer;
    @SerializedName("HomeBGColor") public String homeBGColor;
    @SerializedName("LastName") public String lastName;
    @SerializedName("ParentShopSK") public String parentShopSK;
    @SerializedName("AllowRefferal") public String allowRefferal;
    @SerializedName("SubTitleTextColor") public String subTitleTextColor;
    @SerializedName("ShopConfigSK") public String shopConfigSK;
    @SerializedName("RecallWebURL") public String recallWebURL;
    @SerializedName("Speedometer") public String speedometer;
    @SerializedName("enable_Dashboard") public String enableDashboard;
    @SerializedName("StatusBarBGColor") public String statusBarBGColor;
    @SerializedName("StripePublishableKey") public String stripePublishableKey;
    @SerializedName("firstChat") public String firstChat;
    @SerializedName("AppName") public String appName;
    @SerializedName("RegistrationNotification") public String registrationNotification;
    @SerializedName("AppVersion") public String appVersion;
    @SerializedName("isHide_odometer") public String isHideOdometer;
    @SerializedName("TapHighLightedColor") public String tapHighLightedColor;
    @SerializedName("UNIQUE_PREFIX") public String uNIQUEPREFIX;
    @SerializedName("ProfileImage") public String profileImage;
    @SerializedName("MinPerAppointment") public String minPerAppointment;
    @SerializedName("DateTimeDisplayFormat") public String dateTimeDisplayFormat;
    @SerializedName("MobileNo") public String mobileNo;
    @SerializedName("LengthUnitCode") public String lengthUnitCode;
    @SerializedName("IsSingleShop") public String isSingleShop;
    @SerializedName("Listtype") public String listtype;
    @SerializedName("BannerImage") public String bannerImage;
    @SerializedName("SidebarLogo") public String sidebarLogo;
    @SerializedName("LocaleDesc") public String localeDesc;
    @SerializedName("Logo") public String logo;
    @SerializedName("ForceLogout") public String forceLogout = "0";
    @SerializedName("totalLocationCount") public int totalLocationCount;
    @SerializedName("Created_Date") public String createdDate;
    @SerializedName("AppShortName") public String appShortName;
    @SerializedName("UserName") public String userName;

    public String user = "";  //  For preference and bundle
    public String password = "";  //  For preference and bundle
    public boolean rememberMe = false;  //  For preference and bundle

    @SerializedName("CustomerCount") public int customerCount;
    @SerializedName("CustomerList") public List<Customers> customerList;
}